//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.Sede = new HashSet<Sede>();
        }
    
        public int IdCiudad { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Sede> Sede { get; set; }
    }
}
