//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Sede
    {
        public Sede()
        {
            this.Cliente = new HashSet<Cliente>();
        }
    
        public int IdSede { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdCiudad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual ICollection<Cliente> Cliente { get; set; }

        public List<Sede> ListarSedes()
        {
            List<Sede> lstSedes = new List<Sede>();

            try
            {
                using (var context = new PruebasVariasEntities())
                {
                    lstSedes = context.Sede.ToList();
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

            return lstSedes;
        }
    }
}
